<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Subscription Plans
    |--------------------------------------------------------------------------
    | plan_level: used for hierarchical comparison (higher = more features)
    | limits: -1 means unlimited
    */
    'plans' => [

        'basic' => [
            'name'        => 'Basic Plan',
            'plan_level'  => 1,
            'badge_color' => '#1FA84A',
            'price'       => [
                'monthly' => 2500,
                'yearly'  => 25000,
            ],
            'trial_days' => 14,
            'limits'     => [
                'livestock_records'   => 50,
                'crop_records'        => 50,
                'reports_per_month'   => 10,
                'farm_staff'          => 1,
                'farms'               => 1,
                'ai_scans_per_month'  => 15,
            ],
            'features' => [
                'livestock_registration',
                'crop_records',
                'basic_health_records',
                'feeding_schedule',
                'vaccination_reminders',
                'farm_activity_log',
                'advisory_content',
                'basic_dashboard',
                'faq_chatbot_support',
                'monthly_reports',
                'report_download',
                'mobile_access',
                'marketplace_access',
                'multilingual',
                'email_notifications',
            ],
            'description' => 'Perfect for individual smallholder farmers starting their digital journey.',
            'highlights'  => [
                '15 AI Smart Scans per month',
                '50 Crop & Livestock Records',
                'Marketplace access',
                'Basic farm reports',
                'Download reports',
                'Multilingual support',
                'Email notifications',
            ],
        ],

        'basic_pro' => [
            'name'        => 'Basic Pro Plan',
            'plan_level'  => 2,
            'badge_color' => '#0D9488',
            'price'       => [
                'monthly' => 5000,
                'yearly'  => 50000,
            ],
            'trial_days' => 14,
            'limits'     => [
                'livestock_records'                  => 100,
                'crop_records'                       => 100,
                'reports_per_month'                  => 15,
                'farm_staff'                         => 2,
                'farms'                              => 2,
                'ai_scans_per_month'                 => 25,
                'vet_consultations_per_cycle'        => 3,
                'agronomist_consultations_per_cycle' => 3,
            ],
            'features' => [
                'livestock_registration',
                'crop_records',
                'basic_health_records',
                'feeding_schedule',
                'vaccination_reminders',
                'farm_activity_log',
                'advisory_content',
                'basic_dashboard',
                'faq_chatbot_support',
                'monthly_reports',
                'report_download',
                'mobile_access',
                'marketplace_access',
                'multilingual',
                'email_notifications',
                'ai_scan',
                'ai_reports',
                'pdf_reports',
                'vet_service_requests',
                'agronomist_service_requests',
                'digital_farm_records',
                'performance_dashboard',
                'disease_alerts',
                'priority_email_support',
                'notifications',
            ],
            'description' => 'For farmers who need AI diagnostics, marketplace access, and expert consultations.',
            'highlights'  => [
                '25 AI Smart Scans per month',
                '100 Crop & Livestock Records',
                '3 Vet consultations per month',
                '3 Agronomist consultations per month',
                'Marketplace access',
                'AI & PDF Reports',
                'Priority email support',
            ],
        ],

        'premium' => [
            'name'        => 'Premium Plan',
            'plan_level'  => 3,
            'badge_color' => '#2D9CDB',
            'price'       => [
                'monthly' => 10000,
                'yearly'  => 100000,
            ],
            'trial_days' => 14,
            'limits'     => [
                'livestock_records'                  => -1,
                'crop_records'                       => -1,
                'reports_per_month'                  => -1,
                'farm_staff'                         => 5,
                'farms'                              => 3,
                'ai_scans_per_month'                 => 100,
                'vet_consultations_per_cycle'        => 15,
                'agronomist_consultations_per_cycle' => 15,
            ],
            'features' => [
                'livestock_registration',
                'crop_records',
                'basic_health_records',
                'advanced_health_records',
                'feeding_schedule',
                'vaccination_reminders',
                'farm_activity_log',
                'advisory_content',
                'basic_dashboard',
                'performance_dashboard',
                'faq_chatbot_support',
                'monthly_reports',
                'advanced_reports',
                'report_download',
                'pdf_excel_reports',
                'mobile_access',
                'marketplace_access',
                'marketplace_seller',
                'multilingual',
                'email_notifications',
                'sms_notifications',
                'ai_scan',
                'ai_reports',
                'ai_predictive_analytics',
                'vet_service_requests',
                'agronomist_service_requests',
                'digital_farm_records',
                'breeding_reproduction',
                'production_tracking',
                'inventory_management',
                'financial_records',
                'geo_tagged_farm',
                'direct_messaging',
                'disease_alerts',
                'weather_intelligence',
                'profitability_analysis',
                'benchmarking',
                'priority_support',
            ],
            'description' => 'For commercial farmers, agribusinesses and cooperatives wanting full AI-powered management.',
            'highlights'  => [
                '100 AI Smart Scans per month',
                'Unlimited Crop & Livestock Records',
                '15 Vet consultations per month',
                '15 Agronomist consultations per month',
                'Marketplace Seller Account',
                'AI Predictive Analytics',
                'Weather Intelligence & Disease Alerts',
                'SMS Notifications',
                'Priority Support',
            ],
        ],

        'enterprise' => [
            'name'        => 'Enterprise Plan',
            'plan_level'  => 4,
            'badge_color' => '#7C3AED',
            'price'       => [
                'monthly' => 30000,
                'yearly'  => 300000,
            ],
            'trial_days' => 14,
            'limits'     => [
                'livestock_records'                  => -1,
                'crop_records'                       => -1,
                'reports_per_month'                  => -1,
                'farm_staff'                         => -1,
                'farms'                              => -1,
                'ai_scans_per_month'                 => -1,
                'vet_consultations_per_cycle'        => -1,
                'agronomist_consultations_per_cycle' => -1,
                'users'                              => -1,
            ],
            'features' => [
                'livestock_registration',
                'crop_records',
                'basic_health_records',
                'advanced_health_records',
                'feeding_schedule',
                'vaccination_reminders',
                'farm_activity_log',
                'advisory_content',
                'basic_dashboard',
                'performance_dashboard',
                'advanced_analytics_dashboard',
                'faq_chatbot_support',
                'monthly_reports',
                'advanced_reports',
                'custom_reports',
                'report_download',
                'pdf_excel_reports',
                'bulk_data_upload',
                'mobile_access',
                'marketplace_access',
                'marketplace_seller',
                'multilingual',
                'email_notifications',
                'sms_notifications',
                'ai_scan',
                'ai_reports',
                'ai_predictive_analytics',
                'vet_service_requests',
                'agronomist_service_requests',
                'digital_farm_records',
                'breeding_reproduction',
                'production_tracking',
                'inventory_management',
                'financial_records',
                'geo_tagged_farm',
                'direct_messaging',
                'disease_alerts',
                'weather_intelligence',
                'profitability_analysis',
                'benchmarking',
                'priority_support',
                'premium_technical_support',
                'dedicated_account_manager',
                'multi_branch_management',
                'role_based_access',
                'enterprise_security',
                'api_integration',
                'multi_user_access',
                'unlimited_livestock',
                'unlimited_users',
            ],
            'description' => 'For government agencies, NGOs, research institutions, large cooperatives and agribusiness companies.',
            'highlights'  => [
                'Unlimited AI Smart Scans',
                'Unlimited Users & Records',
                'Unlimited Vet & Agronomist Consultations',
                'Dedicated Account Manager',
                'Advanced Analytics Dashboard',
                'Multi-Branch Management',
                'API Access & Bulk Upload',
                'Enterprise Security & RBAC',
                'Premium Technical Support',
            ],
        ],

        'enterprise_plus' => [
            'name'        => 'Enterprise Plus',
            'plan_level'  => 5,
            'badge_color' => '#0B2447',
            'price'       => [
                'monthly' => 75000,
                'yearly'  => 750000,
            ],
            'trial_days' => 14,
            'limits'     => [
                'livestock_records'                  => -1,
                'crop_records'                       => -1,
                'reports_per_month'                  => -1,
                'farm_staff'                         => -1,
                'farms'                              => -1,
                'ai_scans_per_month'                 => -1,
                'vet_consultations_per_cycle'        => -1,
                'agronomist_consultations_per_cycle' => -1,
                'users'                              => -1,
            ],
            'features' => [
                // Everything in Enterprise
                'livestock_registration',
                'crop_records',
                'basic_health_records',
                'advanced_health_records',
                'feeding_schedule',
                'vaccination_reminders',
                'farm_activity_log',
                'advisory_content',
                'basic_dashboard',
                'performance_dashboard',
                'advanced_analytics_dashboard',
                'executive_dashboard',
                'faq_chatbot_support',
                'monthly_reports',
                'advanced_reports',
                'custom_reports',
                'report_download',
                'pdf_excel_reports',
                'bulk_data_upload',
                'mobile_access',
                'marketplace_access',
                'marketplace_seller',
                'multilingual',
                'email_notifications',
                'sms_notifications',
                'ai_scan',
                'ai_reports',
                'ai_predictive_analytics',
                'ai_decision_intelligence',
                'ml_analytics',
                'custom_ai_models',
                'vet_service_requests',
                'agronomist_service_requests',
                'digital_farm_records',
                'breeding_reproduction',
                'production_tracking',
                'inventory_management',
                'financial_records',
                'geo_tagged_farm',
                'direct_messaging',
                'disease_alerts',
                'weather_intelligence',
                'profitability_analysis',
                'benchmarking',
                'priority_support',
                'premium_technical_support',
                'support_24_7',
                'dedicated_account_manager',
                'dedicated_success_manager',
                'priority_development_support',
                'multi_branch_management',
                'multi_country_operations',
                'role_based_access',
                'enterprise_security',
                'api_integration',
                'custom_integrations',
                'multi_user_access',
                'unlimited_livestock',
                'unlimited_users',
                'white_label',
                'dedicated_cloud_resources',
                'quarterly_reviews',
            ],
            'description' => 'For large organizations, financial institutions, donor agencies and multinational agricultural companies.',
            'highlights'  => [
                'Everything in Enterprise',
                'AI Decision Intelligence & ML Analytics',
                'Custom AI Models',
                'Dedicated Cloud Resources',
                'White Label Option',
                'Custom Integrations',
                'Executive Dashboard',
                '24/7 Technical Support',
                'Dedicated Success Manager',
                'Multi-country Operations',
                'Unlimited Staff Accounts',
            ],
        ],

        // Deprecated legacy keys — kept for backward-compat with existing subscriptions.
        // Not shown in UI. Remove after data migration.
        'pro' => [
            'name'        => 'Pro Plan (Legacy)',
            'plan_level'  => 3,
            'badge_color' => '#2D9CDB',
            'price'       => ['monthly' => 10000, 'yearly' => 100000],
            'trial_days'  => 14,
            'limits'      => [
                'livestock_records'  => -1,
                'crop_records'       => -1,
                'reports_per_month'  => -1,
                'farm_staff'         => 5,
                'farms'              => 3,
                'ai_scans_per_month' => 100,
            ],
            'features'    => ['ai_scan', 'marketplace_access', 'pdf_excel_reports'],
            'description' => 'Legacy plan — superseded by Premium Plan.',
            'highlights'  => [],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Professional Role Plans
    |--------------------------------------------------------------------------
    */
    'professional_starter' => [
        'name'        => 'Professional Starter',
        'plan_level'  => 1,
        'badge_color' => '#1FA84A',
        'price'       => ['monthly' => 15000, 'yearly' => 150000],
        'trial_days'  => 14,
        'limits'      => [
            'product_listings'  => 50,
            'orders_per_month'  => 100,
            'team_members'      => 2,
            'analytics_history' => 90,
        ],
        'features'    => [
            'role_dashboard', 'product_listings', 'order_management',
            'marketplace_presence', 'basic_analytics', 'email_support', 'mobile_access',
        ],
        'description' => 'For professionals and small businesses getting started on the MSAS platform.',
        'highlights'  => [
            'Up to 50 product/service listings',
            'Order & request management',
            'Marketplace presence & discoverability',
            'Basic analytics dashboard',
            'Email & in-app support',
            'Mobile app access',
        ],
    ],

    'professional_business' => [
        'name'        => 'Professional Business',
        'plan_level'  => 2,
        'badge_color' => '#2D9CDB',
        'price'       => ['monthly' => 35000, 'yearly' => 350000],
        'trial_days'  => 14,
        'limits'      => [
            'product_listings'  => -1,
            'orders_per_month'  => -1,
            'team_members'      => 10,
            'analytics_history' => -1,
        ],
        'features'    => [
            'role_dashboard', 'product_listings', 'order_management',
            'marketplace_presence', 'basic_analytics', 'email_support', 'mobile_access',
            'unlimited_listings', 'priority_placement', 'advanced_analytics',
            'pdf_excel_reports', 'api_integration', 'priority_support', 'dedicated_account_manager',
        ],
        'description' => 'Full-featured plan for growing businesses and established professionals.',
        'highlights'  => [
            'Unlimited listings & orders',
            'Priority marketplace placement',
            'Advanced analytics & PDF/Excel reports',
            'Up to 10 team members',
            'API integration access',
            'Dedicated account manager',
            '24/7 priority support',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Statuses
    |--------------------------------------------------------------------------
    */
    'statuses' => [
        'trial'     => ['label' => 'Free Trial',  'color' => '#2D9CDB'],
        'active'    => ['label' => 'Active',       'color' => '#1FA84A'],
        'expired'   => ['label' => 'Expired',      'color' => '#dc2626'],
        'cancelled' => ['label' => 'Cancelled',    'color' => '#94a3b8'],
        'suspended' => ['label' => 'Suspended',    'color' => '#F4A300'],
        'none'      => ['label' => 'No Plan',      'color' => '#64748b'],
    ],
];
